### ISSUE TITLE
Logout method issue

### ISSUE THREAD

**Issue by vikassrivastava18** [nofoobar/JobBoard-Fastapi#2]
Unable to logout a user. Trying to delete the access token, but no luck so far

**Comment by nofoobar** [comment]
> Unable to logout a user. Trying to delete the access token, but no luck so far

Hi Vikas,
Have you tried to delete the cookie or overwrite it with a blank value?
https://stackoverflow.com/questions/67094564/fastapi-deleting-cookies-after-logout-not-working
I have seen some StackOverflow issues regarding this, you can first try them out, If it still doesn't work, Share your repo, I will give it a try.

**Comment by vikassrivastava18** [comment]
The StackOverflow answer helped in resolving the issue. Thanks a lot!
